//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scribble.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scribble.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _595_5956276_png_photo_pencil_eraser_color_clip_art_colour {
            get {
                object obj = ResourceManager.GetObject("595-5956276_png-photo-pencil-eraser-color-clip-art-colour", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to soccer
        ///basketball
        ///tennis
        ///baseball
        ///golf
        ///running
        ///volleyball
        ///badminton
        ///swimming
        ///boxing
        ///ping pong
        ///skiing
        ///ice skating
        ///roller skating
        ///cricket
        ///rugby
        ///pool
        ///darts
        ///football
        ///bowling
        ///hockey
        ///surfing
        ///karate
        ///horse racing
        ///snowboarding
        ///skateboarding
        ///cycling
        ///archery
        ///fishing
        ///gymnastics
        ///figure skating
        ///rock climbing
        ///fencing
        ///water skiing
        ///jet skiing
        ///weight lifting
        ///sky diving
        ///lacrosse
        ///wrestling
        ///squash
        ///handball
        ///sailing
        ///triathlon
        ///ultimate frisbee
        ///hiking
        ///cross-country skiing
        ///snowmobiling
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActionFile {
            get {
                return ResourceManager.GetString("ActionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cat
        ///Cow
        ///Dog
        ///Donkey
        ///Goat
        ///Guinea pig
        ///Horse
        ///Pig
        ///Rabbit
        ///Chicken
        ///Duck
        ///Alligator
        ///Alpaca
        ///Ant
        ///Anteater
        ///Antelope
        ///Ape
        ///Baboon
        ///Bat
        ///Bear
        ///Beaver
        ///Bee
        ///Bird
        ///jellyfish
        ///Bug
        ///Caterpillar
        ///Catfish
        ///Cattle
        ///Chameleon
        ///Cheetah
        ///Chimpanzee
        ///Chipmunk
        ///Clam
        ///Clownfish
        ///Cobra
        ///Cockroach
        ///Crab
        ///Cricket
        ///Crow
        ///Deer
        ///Dinosaur
        ///Dolphin
        ///Donkey
        ///Dragon
        ///Duck
        ///worm
        ///Eel
        ///Elephant
        ///Falcon
        ///Firefly
        ///Fish
        ///Flamingo
        ///Flying fish
        ///Fox
        ///Frog
        ///Gecko
        ///Giraffe
        ///Goat
        ///Goldfish
        ///Gopher
        ///Gorilla
        ///Grasshopper
        ///Guinea pig
        ///Hammer [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnimalFile {
            get {
                return ResourceManager.GetString("AnimalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aroma
        ///apple
        ///avocado
        ///apple pie
        ///bagel
        ///batter
        ///beans
        ///beer
        ///biscuit
        ///bread
        ///broth
        ///burger
        ///burrito
        ///butter
        ///cake
        ///candy
        ///caramel
        ///caviar
        ///cheese
        ///chili
        ///chimichanga
        ///chocolate
        ///cider
        ///cobbler
        ///cocoa
        ///coffee
        ///cookie
        ///cream
        ///croissant
        ///crumble
        ///cuisine
        ///curd
        ///cookie
        ///dessert
        ///dish
        ///drink
        ///donut
        ///dragonfruit
        ///eggs
        ///empanada
        ///enchilada
        ///entree
        ///eclair
        ///filet
        ///fish
        ///flour
        ///foie gras
        ///food
        ///fajitas
        ///falafel
        ///fudge
        ///french onion soup
        ///glaze
        ///grill
        ///garnish
        ///grilled cheese
        ///gnocci
        ///ghost pepper
        ///grapes
        ///grapefrui [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FoodFile {
            get {
                return ResourceManager.GetString("FoodFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image {
            get {
                object obj = ResourceManager.GetObject("image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_processing20200423_22926_hjypki {
            get {
                object obj = ResourceManager.GetObject("image_processing20200423-22926-hjypki", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kissclipart_lapiz_trazo_clipart_pencil_pens_trazo_12fabc162ab2ca86_1_removebg_preview__2_ {
            get {
                object obj = ResourceManager.GetObject("kissclipart-lapiz-trazo-clipart-pencil-pens-trazo-12fabc162ab2ca86-1-removebg-pre" +
                        "view (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast and Furious
        ///Avatar
        ///Spiderman
        ///batman
        ///Percy Jackson
        ///Indiana Jones
        ///Back to the future
        ///The Incredibles
        ///Transformers
        ///Despicable Me
        ///The Lord of the Rings
        ///Wednesday
        ///Groot
        ///Avengers
        ///Marvel
        ///The Matrix
        ///The Dark Knight Rises
        ///Star Trek
        ///Star Wars
        ///Harry Potter
        ///Voldemort
        ///Gollum
        ///Xmen
        ///ET
        ///Ace ventura
        ///The Terminator
        ///The hunger games
        ///Katniss Everdeen
        ///Luke Skywalker
        ///Captain America
        ///Ferris Bueller
        ///Yoda
        ///Rocky
        ///Forrest Gump
        ///Doc Brown
        ///Loki
        ///Superman
        ///The Pirates of the Caribbean
        ///Marty McFly
        ///D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MovieFile {
            get {
                return ResourceManager.GetString("MovieFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bus
        ///lamborghini
        ///bicycle
        ///wallet
        ///pencil and eraser
        ///helmet
        ///washing machine
        ///computer
        ///sweater
        ///toothbrush
        ///arm
        ///ankle
        ///arrow
        ///atm
        ///acid
        ///alphabet
        ///bleach
        ///baby oil
        ///boat
        ///ball
        ///belt
        ///binoculars
        ///bluetooth
        ///battery
        ///castle
        ///clock
        ///cable
        ///clippers
        ///phone
        ///camera
        ///clothes
        ///casino
        ///dishwasher
        ///dogleg
        ///diesel
        ///diamond
        ///dining table
        ///diaper
        ///dipole
        ///deoderant
        ///expressway
        ///enchilada
        ///ear
        ///esophagus
        ///earth
        ///electricity
        ///fire pit
        ///fly swatter
        ///foot locker
        ///fishbowl
        ///fireplace
        ///finger
        ///fire alarm
        ///golfcart
        ///golf c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ObjectFile {
            get {
                return ResourceManager.GetString("ObjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pencil {
            get {
                object obj = ResourceManager.GetObject("pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pencil_drawing_doodle_clip_art_png_favpng_nvHB5btG59KAuiHzEVCy2yzYF_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("pencil-drawing-doodle-clip-art-png-favpng-nvHB5btG59KAuiHzEVCy2yzYF-removebg-prev" +
                        "iew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miley Cyrus
        ///Kim Kardashian
        ///Kayne West
        ///Margaret Thatcher
        ///George Washington
        ///Ghandi
        ///Nelson Mandela
        ///Christopher Columbus
        ///Justin Beiber
        ///Lady Gaga
        ///Katy Perry
        ///Justin Timberlake
        ///Jay Leno
        ///David Letterman
        ///Elle McPherson
        ///Jennifer Aniston
        ///Donald Duck
        ///Goofy
        ///Johnny Depp
        ///Brittney Spears
        ///Paris Hilton
        ///Hugh Jackman
        ///Vladimir Putin
        ///Daniel Radcliffe
        ///David Beckham
        ///Madonna
        ///Eminem
        ///Matt Damon
        ///Serena Williams
        ///Brad Pitt
        ///Mickey Mouse
        ///Simon Cowell
        ///Beethoven
        ///Queen Elizabeth II
        ///Albert Einstein
        ///Bill Gate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PeopleFile {
            get {
                return ResourceManager.GetString("PeopleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statue of liberty
        ///eiffel tower
        ///big ben
        ///leaning tower of pisa
        ///colosseum
        ///golden gate bridge
        ///london eye
        ///great wall of china
        ///sydney opera house
        ///stonehenge
        ///pyramids of giza
        ///taj mahal
        ///mount everest
        ///white house
        ///cn tower
        ///grand canyon
        ///niagara falls
        ///burj khalifa
        ///mount rushmore
        ///new york
        ///toronto
        ///dubai
        ///amsterdam
        ///alcatraz
        ///hollywood
        ///world trade center
        ///disneyland
        ///volcano
        ///desert
        ///swamp
        ///paris
        ///hong kong
        ///rome
        ///tokyo
        ///qatar
        ///las vegas
        ///montreal
        ///chicago
        ///boston
        ///dallas.
        /// </summary>
        internal static string PlaceFile {
            get {
                return ResourceManager.GetString("PlaceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to soccer
        ///basketball
        ///tennis
        ///baseball
        ///golf
        ///running
        ///volleyball
        ///badminton
        ///swimming
        ///boxing
        ///ping pong
        ///skiing
        ///ice skating
        ///roller skating
        ///cricket
        ///rugby
        ///pool
        ///darts
        ///football
        ///bowling
        ///hockey
        ///surfing
        ///karate
        ///horse racing
        ///snowboarding
        ///skateboarding
        ///cycling
        ///archery
        ///fishing
        ///gymnastics
        ///figure skating
        ///rock climbing
        ///fencing
        ///water skiing
        ///jet skiing
        ///weight lifting
        ///sky diving
        ///lacrosse
        ///wrestling
        ///squash
        ///handball
        ///sailing
        ///triathlon
        ///ultimate frisbee
        ///hiking
        ///cross-country skiing
        ///snowmobiling
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RandomFile {
            get {
                return ResourceManager.GetString("RandomFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2023_06_06_094049_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2023-06-06_094049-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Untitled_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Untitled-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
